dist: trusty
language: node_js
node_js: node
install:
- travis_retry gem install s3_website -v 2.12.3
- travis_retry npm install
# Install the AWS CLI tools for explicit CloudFront invalidation
- travis_retry pip install awscli --upgrade --user
before_script: npm run build
script: ./s3_deploy.sh
cache:
  bundler: true
  directories:
    - node_modules
